'use strict';

/**
 * Upload Jesus March photos from a public Google Drive folder to Firebase Storage
 * and write js/nigeria-gallery-manifest.js for the Nigeria landing gallery.
 *
 * Usage (from firebase/functions):
 *   $env:GOOGLE_APPLICATION_CREDENTIALS="..\..\bible-study-dashboard-99f2d-firebase-adminsdk-fbsvc-acf38364bd.json"
 *   node scripts/uploadNigeriaGalleryFromDrive.js --folder="181XV-Tqbr_GPl2A58weTUChUZ7qrZj3C"
 *   node scripts/uploadNigeriaGalleryFromDrive.js --folder="181XV-Tqbr_GPl2A58weTUChUZ7qrZj3C" --commit --limit=24
 */

const fs = require('fs');
const path = require('path');
const admin = require('firebase-admin');
const { GoogleAuth } = require('google-auth-library');

const BUCKET = 'bible-study-dashboard-99f2d.firebasestorage.app';
const STORAGE_PREFIX = 'gallery/nigeria-jesus-march/';
const MANIFEST_PATH = path.join(__dirname, '../../../js/nigeria-gallery-manifest.js');
const DRIVE_API = 'https://www.googleapis.com/drive/v3';
const SCOPES = ['https://www.googleapis.com/auth/drive.readonly'];
const FOLDER_MIME = 'application/vnd.google-apps.folder';

function parseArgs(argv) {
  const out = {};
  for (const arg of argv.slice(2)) {
    const m = arg.match(/^--([^=]+)=(.*)$/);
    if (m) out[m[1]] = m[2];
    else if (arg.startsWith('--')) out[arg.slice(2)] = true;
  }
  return out;
}

function extractFolderId(input) {
  if (!input) return null;
  const cleaned = String(input).trim();
  const folderMatch = cleaned.match(/\/folders\/([a-zA-Z0-9_-]+)/);
  if (folderMatch) return folderMatch[1];
  if (/^[a-zA-Z0-9_-]{10,}$/.test(cleaned)) return cleaned;
  return null;
}

function publicUrl(storagePath) {
  return `https://firebasestorage.googleapis.com/v0/b/${BUCKET}/o/${encodeURIComponent(storagePath)}?alt=media`;
}

function mediaTypeFromMime(mimeType, name) {
  if (mimeType && mimeType.startsWith('image/')) return 'image';
  const lower = String(name || '').toLowerCase();
  if (/\.(jpe?g|png|gif|webp|heic)$/.test(lower)) return 'image';
  if (/\.(mp4|mov|m4v)$/.test(lower)) return 'video';
  return 'other';
}

async function listDriveFiles(auth, folderId) {
  const client = await auth.getClient();
  const q = `'${folderId}' in parents and trashed=false`;
  let pageToken = '';
  const files = [];
  do {
    const url =
      `${DRIVE_API}/files?q=${encodeURIComponent(q)}` +
      '&fields=nextPageToken,files(id,name,mimeType,size,createdTime)' +
      '&pageSize=200' +
      (pageToken ? `&pageToken=${pageToken}` : '');
    const res = await client.request({ url });
    const data = res.data || {};
    for (const f of data.files || []) {
      if (f.mimeType === FOLDER_MIME) continue;
      const type = mediaTypeFromMime(f.mimeType, f.name);
      if (type === 'image' || type === 'video') files.push({ ...f, type });
    }
    pageToken = data.nextPageToken || '';
  } while (pageToken);
  return files;
}

function writeManifest(items) {
  const payload = {
    title: 'Jesus March Nigeria',
    items: items.map((item) => ({
      name: item.name,
      type: item.type,
      src: item.src,
    })),
  };
  const js =
    '/** Auto-generated by firebase/functions/scripts/uploadNigeriaGalleryFromDrive.js */\n' +
    'window.NIGERIA_GALLERY_MANIFEST = ' +
    JSON.stringify(payload, null, 2) +
    ';\n';
  fs.writeFileSync(MANIFEST_PATH, js, 'utf8');
  console.log('Wrote', MANIFEST_PATH, `(${items.length} items)`);
}

async function main() {
  const args = parseArgs(process.argv);
  const folderId = extractFolderId(args.folder);
  if (!folderId) {
    console.error('Pass --folder=<Drive folder id or link>');
    process.exit(1);
  }
  const limit = parseInt(args.limit || '24', 10);
  const commit = !!args.commit;

  if (!admin.apps.length) {
    admin.initializeApp({ storageBucket: BUCKET });
  }
  const bucket = admin.storage().bucket(BUCKET);
  const auth = new GoogleAuth({ scopes: SCOPES });

  const files = await listDriveFiles(auth, folderId);
  files.sort((a, b) => String(a.createdTime).localeCompare(String(b.createdTime)));
  const picked = files.slice(0, limit);
  console.log(`Found ${files.length} media files; using ${picked.length}${commit ? '' : ' (dry run)'}`);

  if (!commit) {
    picked.forEach((f, i) => console.log(`${i + 1}. [${f.type}] ${f.name}`));
    console.log('Add --commit to upload and write manifest.');
    return;
  }

  const client = await auth.getClient();
  const items = [];
  for (const f of picked) {
    const safeName = String(f.name).replace(/[^\w.\-]+/g, '_');
    const storagePath = STORAGE_PREFIX + safeName;
    const downloadUrl = `${DRIVE_API}/files/${f.id}?alt=media`;
    const res = await client.request({ url: downloadUrl, responseType: 'arraybuffer' });
    await bucket.file(storagePath).save(Buffer.from(res.data), {
      metadata: { contentType: f.mimeType || 'application/octet-stream' },
    });
    items.push({ name: path.parse(f.name).name, type: f.type, src: publicUrl(storagePath) });
    console.log('Uploaded', f.name);
  }

  writeManifest(items);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
