'use strict';

/**
 * Upload Day 1 gallery files to Firebase Storage and write js/gallery-day1-manifest.js
 *
 * Usage (from firebase/functions):
 *   set GOOGLE_APPLICATION_CREDENTIALS=..\bible-study-dashboard-99f2d-firebase-adminsdk-fbsvc-acf38364bd.json
 *   node scripts/uploadGalleryDay1.js
 */

const fs = require('fs');
const path = require('path');
const admin = require('firebase-admin');

const BUCKET = 'bible-study-dashboard-99f2d.firebasestorage.app';
const LOCAL_DIR = path.join(__dirname, '../../../images/gallery/day1');
const MANIFEST_OUT = path.join(__dirname, '../../../js/gallery-day1-manifest.js');
const SKIP_NAMES = new Set(['ddbs logo.jpg']);

function contentType(name) {
  const lower = name.toLowerCase();
  if (lower.endsWith('.jpeg') || lower.endsWith('.jpg') || lower.endsWith('.heic')) return 'image/jpeg';
  if (lower.endsWith('.png')) return 'image/png';
  if (lower.endsWith('.mp4')) return 'video/mp4';
  if (lower.endsWith('.mov')) return 'video/quicktime';
  return 'application/octet-stream';
}

function mediaType(name) {
  const ct = contentType(name);
  if (ct.startsWith('image/')) return 'image';
  if (ct.startsWith('video/')) return 'video';
  return 'other';
}

function publicUrl(storagePath) {
  const encoded = encodeURIComponent(storagePath).replace(/%2F/g, '%2F');
  return `https://firebasestorage.googleapis.com/v0/b/${BUCKET}/o/${encoded}?alt=media`;
}

async function main() {
  if (!admin.apps.length) {
    admin.initializeApp({
      storageBucket: BUCKET,
    });
  }

  if (!fs.existsSync(LOCAL_DIR)) {
    console.error('Missing folder:', LOCAL_DIR);
    process.exit(1);
  }

  const bucket = admin.storage().bucket();
  const files = fs
    .readdirSync(LOCAL_DIR)
    .filter((f) => !SKIP_NAMES.has(f))
    .sort((a, b) => a.localeCompare(b));

  const items = [];

  for (const fileName of files) {
    const type = mediaType(fileName);
    if (type === 'other') continue;

    const localPath = path.join(LOCAL_DIR, fileName);
    const dest = `gallery/day1/${fileName}`;
    const stat = fs.statSync(localPath);

    console.log('Uploading', fileName, `(${(stat.size / 1024 / 1024).toFixed(1)} MB)`);

    await bucket.upload(localPath, {
      destination: dest,
      metadata: {
        contentType: contentType(fileName),
        cacheControl: 'public, max-age=31536000, immutable',
      },
      resumable: stat.size > 8 * 1024 * 1024,
    });

    try {
      await bucket.file(dest).makePublic();
    } catch (_) {
      /* public read via storage.rules */
    }

    const url = publicUrl(dest);
    items.push({
      name: fileName.replace(/\.[^.]+$/, ''),
      type,
      src: url,
    });
  }

  items.sort((a, b) => {
    if (a.type !== b.type) return a.type === 'image' ? -1 : 1;
    return a.name.localeCompare(b.name);
  });

  const manifest = {
    ok: true,
    title: 'Day 1 — June 14, 2026',
    items,
  };

  const js =
    '/** Auto-generated by firebase/functions/scripts/uploadGalleryDay1.js */\n' +
    'window.PRAYER_CITY_GALLERY_MANIFEST = ' +
    JSON.stringify(manifest, null, 2) +
    ';\n';

  fs.writeFileSync(MANIFEST_OUT, js, 'utf8');
  console.log('Wrote', MANIFEST_OUT);
  console.log({ uploaded: items.length, images: items.filter((i) => i.type === 'image').length, videos: items.filter((i) => i.type === 'video').length });
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
